spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leasing_application
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never
